author           = InnovAnon
depends          = default,fakery,ia_util
description      = Fakery extensions
name             = ia_counterfeit
optional_depends = mcg_lockworkshop, technic
title            = IA Counterfeit

